name: Production Deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create kube config
        run: |
          KUBECONFIG=$(mktemp -d)/config
          base64 -d <(printf "%s" $KUBE_CONFIG_BASE64_DATA) > $KUBECONFIG
          echo KUBECONFIG=$KUBECONFIG >> $GITHUB_ENV
        env:
          KUBE_CONFIG_BASE64_DATA: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}

      - name: Install werf
        uses: werf/actions/install@v2

      - name: Run werf converge
        run: |
          . $(werf ci-env github --as-file)
          werf converge --platform linux/amd64 --verbose
        env:
          WERF_ENV: production
          GITHUB_TOKEN: ${{ github.token }}
          ENABLEBANKING_PRIVATE_KEY: ${{ secrets.ENABLEBANKING_PRIVATE_KEY }}
          AUTH: ${{ secrets.AUTH }}
